# Site settings
<<<<<<< HEAD
title: HA EUN's Portfolio
=======
title: HA EUN Portfolio 
>>>>>>> 69a335ed9af2824b895959c06d634b5526fa764f
description: A blog about lorem ipsum dolor sit amet
baseurl: "/portfolio" # the subpath of your site, e.g. /blog
url: "http://iheee6-6.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
<<<<<<< HEAD
username: HA EUN SHIN
=======
username: HA EUN
>>>>>>> 69a335ed9af2824b895959c06d634b5526fa764f
user_description: Hansei Univ. Information Communication Engineering 
user_title: Software Developer
email: iheee6@gmail.com
twitter_username: lorem_ipsum
github_username:  iheee6-6
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
